# Generated by Django 3.1.4 on 2020-12-07 19:25

from django.db import migrations, models
import preschool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChildName', models.CharField(max_length=100)),
                ('ParentName', models.CharField(max_length=100)),
                ('Age', models.PositiveIntegerField(validators=[preschool.models.childAge])),
            ],
        ),
    ]
