# Generated by Django 3.1.4 on 2020-12-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preschool', '0002_auto_20201207_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('role', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
